groups:
  - name: blackbox_exporter_alerts
    rules:
      - alert: HostUp
        expr: probe_success{job="blackbox"} == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Host {{ $labels.instance }} is up"
          description: "{{ $labels.instance }} is reachable for more than 1 minute."
      - alert: HostDown
        expr: probe_success{job="blackbox"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Host {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} is unreachable for more than 1 minute."
